Add reporter for multi-checks https://github.com/orgs/community/discussions/8031

diff --git a/.github/workflows/desktop-e2e.yaml b/.github/workflows/desktop-e2e.yaml
--- a/.github/workflows/desktop-e2e.yaml
+++ b/.github/workflows/desktop-e2e.yaml
@@ -1,50 +1,63 @@
 name: Desktop E2E tets
 
 on:
-    push:
-        branches: ["main"]
-    pull_request:
-        branches: ["main"]
+  push:
+    branches: ["main"]
+  pull_request:
+    branches: ["main"]
 
 jobs:
-    desktop-e2e:
-        runs-on: macos-latest
-        # Test on both main's and PR's code
-        strategy:
-            matrix:
-                include:
-                    - branch: main
-                      artifact: main
-                    - branch: ${{ github.head_ref }}
-                      artifact: pull-request
+  desktop-e2e:
+    runs-on: macos-latest
+    # Test on both main's and PR's code
+    strategy:
+      matrix:
+        include:
+          - branch: main
+            artifact: main
+          - branch: ${{ github.head_ref }}
+            artifact: pull-request
 
-        permissions:
-            contents: read
+    permissions:
+      contents: read
 
-        steps:
-            - uses: actions/checkout@v4
-            - name: Install Node.js
-              uses: actions/setup-node@v1
-              with:
-                  node-version: 22
-            - name: Setup pnpm
-              uses: pnpm/action-setup@v4.1.0
-            - name: Install project dependencies
-              run: pnpm install
-            - name: Install Playwright Browsers
-              run: pnpm exec playwright install --with-deps
-            - name: Build monorepo
-              run: pnpm run build
-            - name: Run E2E tests
-              working-directory: apps/desktop
-              env:
-                  DISPLAY: :0
-              run: |
-                  Xvfb :0 -screen 0 1920x1080x24 &
-                  pnpm run e2e
-            - uses: actions/upload-artifact@v4
-              if: ${{ !cancelled() }}
-              with:
-                  name: desktop-playwright-report-${{ matrix.artifact }}-${{ github.run_number }}
-                  path: apps/desktop/playwright-report/
-                  retention-days: 30
+    steps:
+      - uses: actions/checkout@v4
+      - name: Install Node.js
+        uses: actions/setup-node@v1
+        with:
+          node-version: 22
+      - name: Setup pnpm
+        uses: pnpm/action-setup@v4.1.0
+      - name: Install project dependencies
+        run: pnpm install
+      - name: Install Playwright Browsers
+        run: pnpm exec playwright install --with-deps
+      - name: Build monorepo
+        run: pnpm run build
+      - name: Run E2E tests
+        working-directory: apps/desktop
+        env:
+          DISPLAY: :0
+        run: |
+          Xvfb :0 -screen 0 1920x1080x24 &
+          pnpm run e2e
+      - uses: actions/upload-artifact@v4
+        if: ${{ !cancelled() }}
+        with:
+          name: desktop-playwright-report-${{ matrix.artifact }}-${{ github.run_number }}
+          path: apps/desktop/playwright-report/
+          retention-days: 30
+
+  desktop-e2e-finished:
+    needs: desktop-e2e
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check test results
+        run: |
+          if [ "${{ needs.desktop-e2e.result }}" != "success" ]; then
+              echo "E2E tests failed!"
+              exit 1
+          fi
+          echo "All E2E tests passed!"
diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -46,3 +46,16 @@ jobs:
       #   with:
       #       name: coverage-${{ matrix.artifact }}
       #       path: coverage
+
+  test-finished:
+    needs: test
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check test results
+        run: |
+          if [ "${{ needs.test.result }}" != "success" ]; then
+            echo "Tests failed!"
+            exit 1
+          fi
+          echo "All tests passed!"
